### ISSUE TITLE
关于__weak修饰符

### ISSUE THREAD

**Issue by pickView** [mengxianliang/XLRefresh#2]
文件 XLRefreshBase文件下，
__weak UIScrollView *_scrollView;
为什么需要__weak这个修饰符，
期待您的回复

**Comment by mengxianliang** [comment]
例如场景是给UITableview添加下拉刷新，就是给这个tableview添加了一个的强引用属性xl_header。
而与此同时xl_header内部属性_scrollView的用途就指向这个tableview。为了避免造成循环引用，需要用week修饰_scrollView属性.

**Comment by pickView** [comment]
3q,good job
